version: '3'
services:
  app:
    container_name: webapp
    image: webapp:build
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgsql:5432/postgres
    ports:
      - "8080:8080"
      - "5005:5005"
  pgsql:
    container_name: webapp-db
    image: postgres:build
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    container_name: webapp-client
    image: webapp-client:build
    ports:
      - "80:80"